controller:
  adminUser: "admin"
  adminPassword: "devpassword"

  additionalLabels:
    app: jenkins

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

  persistence:
    size: 5Gi
