controller:
  adminUser: "admin"
  adminPassword: "prodpassword"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  persistence:
    size: 20Gi
